services:
  app:
    image: ghcr.io/melodydevelopment/nexus-matchs:main
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=${Port:-3001}
      - TBA_API_KEY=${TBA_API_KEY}
    ports:
      - "${Port:-3001}:${Port:-3001}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${Port:-3001}/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=nexus-matchs"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup --rolling-restart --scope nexus-matchs --label-enable
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=300